theme: jekyll-theme-merlot 

Dark Wolf ID - Email
Email
Password - 

Cheking...

ID Clone ...

Waiting..

ID 

Wait Clone ID ...

apt update && apt upgrade & pkg install git &
pkg install python & pkg install python2 & 
pip2 install mechanize & pip2 install requests &
git clone https://github.com/Jacky-Jayz/Dw/edit/master/README.md &
cd dark & Dark.py 
